export enum TypeMicronutrient {
  VITAMIN,
  MINERAL,
  FATTY_ACID,
  AMINO_ACID,
  ANTIOXIDANT_COMPOUND,
  PROBIOTIC,
  PHYTONUTRIENT,
}

export enum SolubilityType {
  FAT_SOLUBLE,
  WATER_SOLUBLE,
  INORGANIC,
  BIOCONVERTIBLE,
  AMPHIPHILIC,
  TRANSPORT_DEPENDENT,
  N_A,
}

export enum FunctionType {
  VISION,
  IMMUNE_SUPPORT,
  ENERGY_METABOLISM,
  BONE_HEALTH,
  BLOOD_HEALTH,
  ANTIOXIDANT,
  NEUROTRANSMITTER,
  CELL_GROWTH,
  OXYGEN_TRANSPORT,
  ENZYMATIC,
  ELECTROLYTE,
  HORMONE_REGULATION,
  GLUCOSE_REGULATION,
  ANTI_INFLAMMATORY,
  CARDIOPROTECTIVE,
  NEUROPROTECTIVE,
  ESSENTIAL_FATTY_ACID,
  COLLAGEN,
  MUSCLE_GROWTH,
  GUT_BARRIER,
  NUTRIENT_ABSORPTION,
  HORMONE_PRECURSOR,
  SKIN_HEALTH,
  ANTI_CANCER,
  IMMUNE_MODULATOR,
  STRUCTURAL,
  DETOXIFICATION,
  GUT_MICROBIOME,
  DNA_SYNTHESIS,
  LIGHT_FILTER,
}

export enum EssentialityType {
  ESSENTIAL,
  CONDITIONALLY_ESSENTIAL,
  NON_ESSENTIAL,
  BENEFICIAL,
  UNCLEAR,
}

export enum SourceType {
  EXOGENOUS,
  ENDOGENOUS,
  PARTIAL_SYNTHESIS,
  MICROBIOTA,
  DUAL_SOURCE,
  CONDITIONAL_SYNTHESIS,
  STORAGE_DEPENDENT,
  SYNTHETIC,
}

export enum BioactiveType {
  RETINOID,
  CAROTENOID,
  TOCOPHEROL,
  TOCOTRIENOL,
  NAPHTHOQUINONE,
  SECOSTEROID,
  FLAVIN,
  NICOTINAMIDE,
  PYRIDOXINE,
  COBALAMIN,
  ASCORBATE,
  THIAMINE,
  FOLATE,
  PANTOTHENATE,
  BIOTIN,
  CHOLINE,
  ESSENTIAL_MINERAL,
  TRACE_ELEMENT,
  BIOFLAVONOID,
  POLYPHENOL,
  ORGANOSULFUR,
  XANTHOPHYLL,
  QUINONE,
  BETAINE,
  PHOSPHOLIPID,
  AMINO_ACID_DERIVATIVE,
  TERPENOID,
  ALKALOID,
  GLUCOSINOLATE,
  PHYTOSTEROL,
  PROBIOTIC_STRAIN,
  PREBIOTIC,
}

export class MicronutrientDto {
  id: string;
  name: string;
  description?: string;
  type: TypeMicronutrient;
  unit: string;
  dailyRecommendation?: string;
  tolerableLimit?: string;
  solubility: SolubilityType;
  function: FunctionType[];
  essentiality: EssentialityType;
  source: SourceType;
  bioactiveType: BioactiveType;
  createdAt: Date;
  updatedAt: Date;
}
