export enum AllergenType {
  NONE = 'NONE',
  GLUTEN = 'GLUTEN',
  LACTOSE = 'LACTOSE',
  NUTS = 'NUTS',
  PEANUTS = 'PEANUTS',
  SOY = 'SOY',
  EGGS = 'EGGS',
  FISH = 'FISH',
  SHELLFISH = 'SHELLFISH',
  CELERY = 'CELERY',
  MUSTARD = 'MUSTARD',
  SESAME = 'SESAME',
  SULFITES = 'SULFITES',
  LUPIN = 'LUPIN',
  MOLLUSCS = 'MOLLUSCS',
}

export enum OriginType {
  ANIMAL = 'ANIMAL',
  VEGETAL = 'VEGETAL',
  SYNTHETIC = 'SYNTHETIC',
  MINERAL = 'MINERAL',
  MICROBIAL = 'MICROBIAL',
}

export enum AdditiveType {
  NONE = 'NONE',
  SWEETENER = 'SWEETENER',
  PRESERVATIVE = 'PRESERVATIVE',
  COLORANT = 'COLORANT',
  EMULSIFIER = 'EMULSIFIER',
  FLAVOR_ENHANCER = 'FLAVOR_ENHANCER',
  STABILIZER = 'STABILIZER',
  THICKENER = 'THICKENER',
  ACIDULANT = 'ACIDULANT',
  BULKING_AGENT = 'BULKING_AGENT',
  COATING_AGENT = 'COATING_AGENT',
  ANTI_CAKING_AGENT = 'ANTI_CAKING_AGENT',
  ANTI_FOAMING_AGENT = 'ANTI_FOAMING_AGENT',
  ANTIOXIDANT = 'ANTIOXIDANT',
  CLARIFYING_AGENT = 'CLARIFYING_AGENT',
  COAGULANT = 'COAGULANT',
  COLOR_FIXATIVE = 'COLOR_FIXATIVE',
  GASES = 'GASES',
  RAISING_AGENT = 'RAISING_AGENT',
  GELLING_AGENT = 'GELLING_AGENT',
  HUMECTANT = 'HUMECTANT',
  ACIDITY_REGULATOR = 'ACIDITY_REGULATOR',
  FLAVORING = 'FLAVORING',
  MELTING_SALT = 'MELTING_SALT',
  SEQUESTRANT = 'SEQUESTRANT',
  FLOUR_TREATMENT_AGENT = 'FLOUR_TREATMENT_AGENT',
  VARIOUS = 'VARIOUS',
}

export enum RiskLevel {
  NONE = 'NONE',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum RiskType {
  CARCINOGENIC = 'CARCINOGENIC',
  ALLERGENIC = 'ALLERGENIC',
  INFLAMMATORY = 'INFLAMMATORY',
  ENDOCRINE_DISRUPTOR = 'ENDOCRINE_DISRUPTOR',
  NEUROTOXIC = 'NEUROTOXIC',
  MUTAGENIC = 'MUTAGENIC',
  HEPATOTOXIC = 'HEPATOTOXIC',
  CARDIOTOXIC = 'CARDIOTOXIC',
  OBESOGENIC = 'OBESOGENIC',
  HIGH_GI = 'HIGH_GI',
  ADDICTIVE = 'ADDICTIVE',
  CONTAMINANTS = 'CONTAMINANTS',
  ANTINUTRIENTS = 'ANTINUTRIENTS',
}

// Spanish translations for documentation
export const EnumTranslations = {
  AllergenType: {
    NONE: 'Ninguno',
    GLUTEN: 'Gluten',
    LACTOSE: 'Lactosa',
    NUTS: 'Frutos secos',
    PEANUTS: 'Cacahuetes',
    SOY: 'Soja',
    EGGS: 'Huevos',
    FISH: 'Pescado',
    SHELLFISH: 'Marisco',
    CELERY: 'Apio',
    MUSTARD: 'Mostaza',
    SESAME: 'Sésamo',
    SULFITES: 'Sulfitos',
    LUPIN: 'Altramuces',
    MOLLUSCS: 'Moluscos',
  },
  OriginType: {
    ANIMAL: 'Animal',
    VEGETAL: 'Vegetal',
    SYNTHETIC: 'Sintético',
    MINERAL: 'Mineral',
    MICROBIAL: 'Microbial',
  },
  AdditiveType: {
    NONE: 'No es aditivo',
    SWEETENER: 'Edulcorante',
    PRESERVATIVE: 'Conservante',
    COLORANT: 'Colorante',
    EMULSIFIER: 'Emulsionante',
    FLAVOR_ENHANCER: 'Potenciador del sabor',
    STABILIZER: 'Estabilizador',
    THICKENER: 'Espesante',
    ACIDULANT: 'Acidulante',
    BULKING_AGENT: 'Agente de carga',
    COATING_AGENT: 'Agente de recubrimiento',
    ANTI_CAKING_AGENT: 'Antiaglomerante',
    ANTI_FOAMING_AGENT: 'Antiespumante',
    ANTIOXIDANT: 'Antioxidante',
    CLARIFYING_AGENT: 'Clarificante',
    COAGULANT: 'Coagulante',
    COLOR_FIXATIVE: 'Fijador de color',
    GASES: 'Gases',
    RAISING_AGENT: 'Gasificante',
    GELLING_AGENT: 'Gelificante',
    HUMECTANT: 'Humectante',
    ACIDITY_REGULATOR: 'Regulador de acidez',
    FLAVORING: 'Saborizante',
    MELTING_SALT: 'Sal de fundido',
    SEQUESTRANT: 'Secuestrante',
    FLOUR_TREATMENT_AGENT: 'Tratamiento de harinas',
    VARIOUS: 'Varios',
  },
  RiskLevel: {
    NONE: 'Ninguno',
    LOW: 'Bajo',
    MEDIUM: 'Medio',
    HIGH: 'Alto',
  },
  RiskType: {
    CARCINOGENIC: 'Carcinogénico',
    ALLERGENIC: 'Alergénico',
    INFLAMMATORY: 'Inflamatorio',
    ENDOCRINE_DISRUPTOR: 'Disruptor endocrino',
    NEUROTOXIC: 'Neurotóxico',
    MUTAGENIC: 'Mutagénico',
    HEPATOTOXIC: 'Hepatotóxico',
    CARDIOTOXIC: 'Cardiotóxico',
    OBESOGENIC: 'Obesogénico',
    HIGH_GI: 'Alto índice glucémico',
    ADDICTIVE: 'Adictivo',
    CONTAMINANTS: 'Contaminantes',
    ANTINUTRIENTS: 'Antinutrientes',
  },
};
