export enum AllergenType {
  NONE = 'NONE',
  GLUTEN = 'GLUTEN',
  LACTOSE = 'LACTOSE',
  NUTS = 'NUTS',
  PEANUTS = 'PEANUTS',
  SOY = 'SOY',
  EGGS = 'EGGS',
  FISH = 'FISH',
  SHELLFISH = 'SHELLFISH',
  CELERY = 'CELERY',
  MUSTARD = 'MUSTARD',
  SESAME = 'SESAME',
  SULFITES = 'SULFITES',
  LUPIN = 'LUPIN',
  MOLLUSCS = 'MOLLUSCS',
}

export enum OriginType {
  ANIMAL = 'ANIMAL',
  VEGETAL = 'VEGETAL',
  SYNTHETIC = 'SYNTHETIC',
  MINERAL = 'MINERAL',
  MICROBIAL = 'MICROBIAL',
}

export enum AdditiveType {
  NO = 'NO',
  SWEETENER = 'SWEETENER',
  PRESERVATIVE = 'PRESERVATIVE',
  COLORANT = 'COLORANT',
  EMULSIFIER = 'EMULSIFIER',
  FLAVOR_ENHANCER = 'FLAVOR_ENHANCER',
  STABILIZER = 'STABILIZER',
  THICKENER = 'THICKENER',
}

export enum RiskLevel {
  NONE = 'NONE',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum RiskType {
  CARCINOGENIC = 'CARCINOGENIC',
  ALLERGENIC = 'ALLERGENIC',
  INFLAMMATORY = 'INFLAMMATORY',
  ENDOCRINE_DISRUPTOR = 'ENDOCRINE_DISRUPTOR',
  NEUROTOXIC = 'NEUROTOXIC',
  MUTAGENIC = 'MUTAGENIC',
  HEPATOTOXIC = 'HEPATOTOXIC',
  CARDIOTOXIC = 'CARDIOTOXIC',
  OBESOGENIC = 'OBESOGENIC',
  HIGH_GI = 'HIGH_GI',
  ADDICTIVE = 'ADDICTIVE',
  CONTAMINANTS = 'CONTAMINANTS',
  ANTINUTRIENTS = 'ANTINUTRIENTS',
}
